version = 0.1

[default.deploy.parameters]
stack_name = "file-processing-python"
resolve_s3 = true
s3_prefix = "file-processing-python"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
